CREATE DATABASE OnlineQuiz
COLLATE Persian_100_CI_AI;

USE OnlineQuiz
GO

CREATE TABLE dbo.Person (
  ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  FirstName NVARCHAR(50) NOT NULL,
  LastName NVARCHAR(50) NOT NULL,
  SSN NVARCHAR(10) NOT NULL
);
GO

CREATE TABLE dbo.Exam (
  ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  Title NVARCHAR(100) NOT NULL,
  CreatedAt DATETIME DEFAULT(GETDATE()) NOT NULL
);
GO

CREATE TABLE dbo.Course(
  ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  Title NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE dbo.Question(
  ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  CourseID INT REFERENCES dbo.Course(ID) NOT NULL,
  Body NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE dbo.Answer(
  ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  Body NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE dbo.Point(
  ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  ExamID INT REFERENCES dbo.Exam(ID) NOT NULL,
  PersonID INT REFERENCES dbo.Person(ID) NOT NULL,
  CourseID INT REFERENCES dbo.Course(ID) NOT NULL,
  TotalPoint INT NOT NULL,
  CreatedAt DATETIME DEFAULT(GETDATE()) NOT NULL
  
);
GO

CREATE TABLE dbo.Exam_Course(
  ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  ExamID INT REFERENCES dbo.Exam(ID) NOT NULL,
  CourseID INT REFERENCES dbo.Course(ID) NOT NULL,
);
GO

CREATE TABLE dbo.Question_Answer(
  ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  AnswerID INT REFERENCES dbo.Answer(ID) NOT NULL,
  QuestionID INT REFERENCES dbo.Question(ID) NOT NULL,
  IsCorrectAnswer BIT NOT NULL DEFAULT(0)
);
GO

CREATE TABLE dbo.Exam_Person(
  ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  ExamID INT REFERENCES dbo.Exam(ID) NOT NULL,
  PersonID INT REFERENCES dbo.Person(ID) NOT NULL,
);
GO
